# Generated by Django 4.2.6 on 2024-02-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_owner_alter_book_author_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, verbose_name='نام نظر دهنده')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='آدرس ایمیل نظر دهنده')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='نام کتاب')),
            ],
        ),
    ]
